[project]
name = 'food-safety-culture'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.performance-analytics]
path = 'contracts/performance-analytics.clar'
clarity_version = 2
epoch = 2.5

[contracts.safety-assessment]
path = 'contracts/safety-assessment.clar'
clarity_version = 2
epoch = 2.5

[contracts.training-management]
path = 'contracts/training-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
